title: "Reinforcement Learning"
date: 2022-02-20
author: "Vuong Dinh An"
email: an.vd180003@sis.hust.edu.vn
description: > # this means to ignore newlines until "baseurl:"
  Reinforcement Learning, Markov Decision Process, Q-learning, TD, Value Iteration
# social links
twitter_username: andy_vg_dev3 # DO NOT include the @ character, or else the build will fail!
github_username: anavuongdin # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
